baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Gat Method'
theme = 'hugo-blog-awesome'

[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/pages/about'
  weight = 20
[[menu.main]]
  name = 'Workshops'
  pageRef = '/pages/workshops'
  weight = 30
[[menu.main]]
  name = 'People'
  pageRef = '/pages/people'
  weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
